### ISSUE TITLE
crash axis after install probe screen

### ISSUE THREAD

**Issue by inscrut** [verser-git/probe_screen_v2.8#1]
log

```
Starting LinuxCNC...
Starting LinuxCNC server program: linuxcncsvr
Loading Real Time OS, RTAPI, and HAL_LIB modules
Starting LinuxCNC IO program: io
Starting HAL User Interface program: halui
linuxcnc TPMOD=tpmod HOMEMOD=homemod EMCMOT=motmod
Found file(REL): ./bf20v.hal
Found file(REL): ./custom.hal
Starting TASK program: milltask
Starting DISPLAY program: axis

emc/task/emctaskmain.cc 3085: can't initialize interpreter
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
waiting for s.joints<0>, s.kinematics_type<0>
Shutting down and cleaning up LinuxCNC...
config string '0x378 out'
Removing HAL_LIB, RTAPI, and Real Time OS modules
Removing NML shared memory segments

Debug file information:
Note: Using POSIX realtime
initialize: module '/home/cnc/linuxcnc/configs/bf20v/python/toplevel.py' init failed: 
Traceback (most recent call last):

  File "/home/cnc/linuxcnc/configs/bf20v/python/toplevel.py", line 19, in <module>
    import remap

  File "/home/cnc/linuxcnc/configs/bf20v/./python/remap.py", line 19, in <module>
    from stdglue import *

  File "/home/cnc/linuxcnc/configs/bf20v/./python/stdglue.py", line 28

    except Exception,e:

           ^^^^^^^^^^^

SyntaxError: multiple exception types must be parenthesized

Interp ctor: can't instantiate Python plugin
initialize: module '/home/cnc/linuxcnc/configs/bf20v/python/toplevel.py' init failed: 
Traceback (most recent call last):

  File "/home/cnc/linuxcnc/configs/bf20v/python/toplevel.py", line 19, in <module>
    import remap

  File "/home/cnc/linuxcnc/configs/bf20v/./python/remap.py", line 19, in <module>
    from stdglue import *

  File "/home/cnc/linuxcnc/configs/bf20v/./python/stdglue.py", line 28

    except Exception,e:

           ^^^^^^^^^^^

SyntaxError: multiple exception types must be parenthesized

Python plugin configure() failed, status = -11
Python plugin required for prolog=, but not available: 86:REMAP = M6   modalgroup=6  prolog=change_prolog   ngc=psng_manual_change  epilog=change_epilog
Python plugin required for epilog=, but not available: 86:REMAP = M6   modalgroup=6  prolog=change_prolog   ngc=psng_manual_change  epilog=change_epilog
<commandline>:0: waitpid failed milltask inihal
<commandline>:0: milltask exited without becoming ready
note: MAXV     max: 31.000 units/sec 1860.000 units/min
note: LJOG     max: 31.000 units/sec 1860.000 units/min
note: LJOG default: 3.100 units/sec 186.000 units/min
note: AJOG     max: 90.000 units/sec 5400.000 units/min
note: AJOG default: 9.000 units/sec 540.000 units/min
A configuration error is preventing LinuxCNC from starting.
More information may be available when running from a terminal.
3926
Stopping realtime threads
Unloading hal components
Note: Using POSIX realtime

```

Делал по инструкции, но что то не хватает

может быть уже была проблема но нагуглить не смог

**Comment by verser-git** [comment]
This looks like a Python2 vs Python3 difference.
Please note that Probe Screen v2.8 will only work with linuxcnc v2.8, not v2.9 or higher.

**Comment by inscrut** [comment]
May be, i would like it for 2.9 version :)

**Comment by inscrut** [comment]
closed
